manifest = "c8ae238dff75d8823a9a8e87fecd356e7f51ae41250cbfac5b583ead8f8ca429"

[[dependency]]
package = "github.com/buckaroo-pm/freetype2"
target = "//:freetype"

[[dependency]]
package = "github.com/buckaroo-pm/icu4c"
target = "//:icu4c"

[[lock]]
name = "github.com/buckaroo-pm/freetype2"
revision = "3f7996f55a627ae14af58d6f63f4830c67936869"

[[lock]]
name = "github.com/buckaroo-pm/icu4c"
revision = "bc4345696f5403768689468a51e173026491cf11"
