manifest = "c8ae238dff75d8823a9a8e87fecd356e7f51ae41250cbfac5b583ead8f8ca429"

[[dependency]]
package = "github.com/buckaroo-pm/freetype2"
target = "//:freetype"

[[dependency]]
package = "github.com/buckaroo-pm/icu4c"
target = "//:icu4c"

[lock."github.com/buckaroo-pm/freetype2"]
versions = [ "branch=master" ]
revision = "3f7996f55a627ae14af58d6f63f4830c67936869"

[lock."github.com/buckaroo-pm/icu4c"]
versions = [ "branch=master" ]
revision = "d6803681f02ef9395665d4db6e84a4416a679bc3"
